POST http://localhost:8080/auth/register
Content-Type: application/json

{
  "username": "singatroon",
  "email": "email@gmail.com",
  "password": "pw"
}

###

POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "email": "email@gmail.com",
  "password": "pw"
}

###

GET http://localhost:8080/auth/protected
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjJmMzZlYTA1NzMwOGRhMGVhODg2YjI2In0sImlhdCI6MTY2MDEyMDczNiwiZXhwIjoxNjYwNzI1NTM2fQ.gREz_LL4tneEnF8OjzsxotupB0KGHJtEcB7k8UMLWEY

###

GET http://localhost:8080/live/streams

###

GET http://localhost:8080/live/thumb/fcfa70e1-b291-4e9c-8a7d-b211abe57986

###

GET http://localhost:8080/live/stream/fcfa70e1-b291-4e9c-8a7d-b211abe57986/playlist.m3u8